### ISSUE TITLE
Two players received the same answer card "socks"

### ISSUE THREAD

**Issue by mmcconnell1618** [jakelauer/allbadcards#139]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/ordinary-puma-62

2. Describe the problem you experienced
Duplicate answer cards

3. Did you see any errors?
Yes, answer cards should be unique within a round and/or game.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by mbax** [comment]
Just saw the same occur in a game as well.

**Comment by jakelauer** [comment]
@mbax was yours with another card, or Socks also?

**Comment by mbax** [comment]
It was not socks. I cannot recall what the card was, but I believe it occurred in `foolish-firefox-72` from my history. Only thought to chime in later on when I saw the issue tracker :D

**Comment by jakelauer** [comment]
Socks was likely a duplicate because it is in both the [Seasons Greetings pack](https://github.com/jakelauer/allbadcards/blob/master/server/data/official/packs/seasons_greetings_pack.json#L62) and the [2012 Holiday Pack](https://github.com/jakelauer/allbadcards/blob/master/server/data/official/packs/2012_holiday_pack.json#L61)

My suspicion is that @mbax had a similar issue of 2 cards that were duplicates in the packs

**Comment by jakelauer** [comment]
Closing this, can reopen if there is further evidence
