### ISSUE TITLE
Sound alerts (or notifications) for when the game state changes

### ISSUE THREAD

**Issue by ikki4** [jakelauer/allbadcards#185]
For example, when I have the black card and I'm waiting for others to pick their white cards, sometimes it takes a couple minutes for them to choose, and only then I can see their choices and pick the winner. While I'm waiting I'd like to do other things, browse other websites or whatever, and from time to time I have to go back to the game to see if I can proceed (and some people forget to do that so it's even more time that everyone's wasting). So it would be nice if the game played sound alerts or notifications to the players in these important states.

If I'm the leader (I mean the one with the black card, not the one with the most points), I'd like to be notified that I can choose the winner, and if I'm not the leader I'd like to be notified that the leader is picking (or has picked) a winner for that round, and that a new round has begun and I can pick a card.

**Comment by jakelauer** [comment]
I have been thinking about this for a while, trying to figure out how to do it in a way that won't annoy the hell out of everyone. I think the answer is that the notification has to be funny somehow. I'll keep thinking on it!

**Comment by haydius** [comment]
Could start by adding an additional switch for sound on/off near your dark mode switch.

Regarding the sounds to use, until you source some funny, ear-catching ones, you could use a little front-end JS to implement some browser-generated sounds.

Code below isn't the neatest but functions well. Uses the **_OscillatorNode_** Web API and supports wave type (sine,sawtooth,triangle,square), a frequency and dropoff duration (seconds)

```javascript
var ctx=new AudioContext();var osc=null;var gain=null;
function makeSound(wave = 'sine',freq = '830',dura){
	osc=ctx.createOscillator()
	gain=ctx.createGain()
	osc.connect(gain)
	osc.type=wave
	osc.frequency.value=freq
	gain.connect(ctx.destination)
	osc.start(0)
	gain.gain.exponentialRampToValueAtTime(0.00001,ctx.currentTime+dura)
	}
```
and some examples...

**Single Ping**
```javascript
makeSound('sine',840,1)
```

**Double Ping**
```javascript
makeSound('sine',1840,1)
setTimeout(function () {makeSound('sine',1840,1)}, 200);

**Triple tone**
```javascript
makeSound('sine',840,1)
setTimeout(function () {makeSound('sine',1040,1)}, 120);
setTimeout(function () {makeSound('sine',1240,1)}, 240);
```

Try it out in the developer console of a browser!
Let me know if I can help in any way :)

**Comment by jakelauer** [comment]
Adding, thanks!

**Comment by castrogstar** [comment]
You can also use the [Onesignal](https://onesignal.com/?utm_source=google&utm_medium=cpc&utm_campaign=branded&gclid=CjwKCAjwiMj2BRBFEiwAYfTbCsFw2FxhGIzMIo-HMXfre0I3jpH6LE7NN2_t2Aq882NAwEQh61fXUxoCwIcQAvD_BwE) service (free of charge) to send push notifications to android devices, as well as desktop notifications for all OS. Only downside is push won't work for iOS since Apple wants to be cool and not support mobile web push (yet). 

Onesignal is an amazing solution for mobile web apps because you can easily add it to any website without the need for building native apps. On top of this, you can also use it to send users promotional messages/updates, etc once they have opted-in to receive notifications from your domain.
