### ISSUE TITLE
Dealing white cards is unfairly favouring small packs

### ISSUE THREAD

**Issue by neilstudd** [jakelauer/allbadcards#241]
I'll file this as a feature request, it's currently "working as designed" but it feels like a bug to me :)

Looking at the code in getAllowedCard, it appears that currently it:

1. Selects a pack at random.
2. Selects a random card from that pack.

The problem is, this means that a card from a small pack has a much higher chance of appearing than it should. Let me show you an example using the Blackbox Press Kit (a selected-by-default pack which contains a single white card, something about Doritos and candles, which appears in EVERY. DAMN. GAME.)

Suppose you select 10 packs, and those packs contain a total of 800 cards. On any given deal, the odds of picking the "Doritos and candles" card should be 1 in 800. However, because the randomiser first selects a random pack (out of 10), the chances of that card being dealt are currently 1 in 10, meaning it currently appears much more than it should (the same is true for cards in any small pack).

**Suggestion: Change getAllowedCard to build a list of all available cards (from all available packs), and then perform a single random selection from that list.**

Also, when playing with multiple expansions IRL, you'd normally shuffle them all into one big pile to pick from - so the behaviour I'm describing would be more consistent with that.

**Comment by jakelauer** [comment]
That's a good point. I'll fix that up :)

**Comment by haydius** [comment]
Not sure if you already have a plan for this one but thought I'd share my idea.
Rough on the edges but was a "think on the run" answer

Get a weighted random by using the total cards in each deck as its weight.
i.e. when `getAllowedCard` is grabbing the deck, rather than random have it run the weightedRandom

I've only just got aroung to setting up a dev machine to have a fiddle with this and unfortunately I've never dealt with asynchronous or server-side JS so I need to learn!
I was trying to use a Promise like a normal object/array -_-

Vanilla JS Example/Mock of my idea for reference:
```javascript
// Static array for demo purpose.
//Would actually be the `deckId` and totals for each allowed deck
var weightedPacks = {pack1:17,pack2:22,pack3:5,pack4:76,pack5:15};

// Quick and dirty - I call it this because it simply adds the
// deck to the array for a count of each card there is in it
function getWeightedRandom(packs) {
  var weightedPackArray = [];
  for(var pack in packs) {
    for( var i=0; i<packs[pack]; i++ ) {
      weightedPackArray.push(pack);
      }
    }
    return weightedPackArray[Math.floor(Math.random() * weightedPackArray.length)];
}
```
|Pack|Cards|Times Picked|Picked Percent|Deck % of game|
|---|---|---|---|---|
|pack1|17|123|12.3%|12.5%
|pack2|22|154|15.4%|16.3%
|pack3|5|44|4.4%|3.7%|
|pack4|76|579|59.7%|56.3|
|pack5|15|100|10%|11.1%|

Mashing all remaining cards into one array and picking one at random may also work but I feel that selecting a deck at (calculated) random first then choosing a card will give a better median spread over all card choices.

**Comment by jakelauer** [comment]
That's a great solution! As part of a refactor pass, I also took a swing at this issue in the dev branch: https://github.com/jakelauer/allbadcards/blob/dev/server/Engine/Games/Cards/CardManager.ts

My method was basically to convert the card pack objects (packId -> ( cardIndex -> Card )) to a flat hash table (packAndCardIndex -> Card), then pick a random card from the values, which had the benefit of requiring fewer loops during the final filter when filtering out used cards from available cards.

Sidenote, if you're at all interested in checking out the code and/or participating in development in some capacity, I would be happy to see PRs from you!

**Comment by jakelauer** [comment]
@neilstudd this is now live!

Here's the updated behavior: https://github.com/jakelauer/allbadcards/blob/49e371cd68be3f4317134b37e2f5b0dea85aa713/server/Engine/Games/Cards/CardManager.ts#L9
