### ISSUE TITLE
Extra Answer(s)

### ISSUE THREAD

**Issue by Scott-N** [jakelauer/allbadcards#244]
My idea is...
Occasionally you have so many good choices for the current round that you really shouldn't have to choose only one of them. This feature would allow you to submit two (or more?) answers for the current round. Not for _every_ turn, but maybe only once, or maybe at the end of the game, or maybe in exchange for one of your points, etc.

**Comment by haydius** [comment]
As in having a game setting to grant some (3 or maybe custom amount) tokens that they can use in that game to throw down an extra card?

I was thinking something similar to this the other night but more from a "help the underdog" kind of position where the player(s) at the bottom of the scoreboard would be given option to submit an additional card to better their chance of a win. Would encourage players on the lower end to keep playing rather than feel like there is no hope and/or "rage quit"

**Comment by Scott-N** [comment]
The tokens idea could work.

I got the original idea just as we were ending a game. (I should explain that instead of ending the game automatically when someone gets X points, we set X really high, like 50, with the intent of ending the game arbitrarily when everyone is pooped out from too much laughing. So we had agreed "this is the last round.") Coincidentally, on the previous round, I had used the "My cards suck" feature, so I had a ton of new/good cards for the last round, and I wished I could submit multiple answers, to maximize the laughs and go out with a bang, so to speak. This feature wouldn't be intended to improve the competitive aspects of the game; it's more for people who are playing for laughs.

If rage quitting is a thing, maybe there should be a "snowflake mode" with no points and everyone gets a trophy at the end. :)

**Comment by jakelauer** [comment]
I think this is a good example of a house rule that is really hard to translate to an online version of the game. For example, what happens with 2- or 3-card prompts? Do you play 4 cards? 6? Do you make sure you play them in order?

Because of these questions, I'm gonna close this for now. I would love to be able to do it, but it would add a ton of complexity to the system for a pretty small payoff.
