### ISSUE TITLE
Can't get project code to build

### ISSUE THREAD

**Issue by theagentalpha** [jakelauer/allbadcards#290]
I cloned your repo and was trying to get it running locally.  Tried on two different machines but `yarn build` kept failing with the error below.  Any thoughts?

```
Failed to compile.

C:/Path/allbadcards/client/node_modules/jest-diff/build/diffLines.d.ts
TypeScript error in C:/Path/allbadcards/client/node_modules/jest-diff/build/diffLines.d.ts(8,13):
'=' expected.  TS1005

     6 |  */
     7 | import { Diff } from './cleanupSemantic';
  >  8 | import type { DiffOptions } from './types';
       |             ^
     9 | export declare const diffLinesUnified: (aLines: string[], bLines: string[], options?: DiffOptions | undefined) => string;
    10 | export declare const diffLinesUnified2: (aLinesDisplay: string[], bLinesDisplay: string[], aLinesCompare: string[], bLinesCompare: string[], options?: DiffOptions
| undefined) => string;
    11 | export declare const diffLinesRaw: (aLines: string[], bLines: string[]) => Diff[];


error Command failed with exit code 1.
```

**Comment by jakelauer** [comment]
This looks like something to do with a new Jest version that uses a newer TypeScript version that we are using. Jest isn't really used for any material purpose in this project but it's still there because it's present in Create React App.

My first idea would be to see what happens if you upgrade the version of `typescript` in the package.config files.

**Comment by theagentalpha** [comment]
Ah, yes upgrading Typescript seems to have done the trick.  Thanks!!
