### ISSUE TITLE
Clarify Add From Json

### ISSUE THREAD

**Issue by jakelauer** [jakelauer/allbadcards#310]
My idea is...
Make sure everyone knows it replaced cards

**Comment by dennmuel** [comment]
Sorry to bump this, but reading the new description it sounds contradictive to what I believe this issue was about. Does uploading now actually replace cards or does it produce duplicates?

If latter is true, I personally would really dig a way to delete the complete deck before uploading the json. (That behaviour already annoyed me with cardcast. But that's just personal preference since I like my packs sorted and managed with git and so on.)

Also displaying validation errors would be really handy.

**Comment by jakelauer** [comment]
Agree - modified to allow add and replace.

Also, validation were set to display, but the schema was slightly wrong. I fixed it!
