### ISSUE TITLE
Yarn errors when building

### ISSUE THREAD

**Issue by jgrifft** [jakelauer/allbadcards#311]
Trying to build this on my own server for fun and receiving the below error when running yarn clean.  I believe everything is installed correctly and was wondering if there was anything you could help provide in terms of a fix or resolution for this.

# yarn clean
yarn run v1.22.4
$ if exist output rmdir /s /q output
/bin/sh: -c: line 1: syntax error: unexpected end of file
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jakelauer** [comment]
It looks like you're on a Unix system. You would just want to change it to whatever command will delete the output folder for your system.

**Comment by dbaratta** [comment]
I'd also add I tried to build it over the weekend on Ubuntu 18.10 but it kept failing since one of the dependencies is `7zip-bin-win` in the `package.json` file.

**Comment by jakelauer** [comment]
You should be able to switch to `7zip-bin-linux` instead and try it :) 

For the record, neither of these operations are super important. The deletion of the output folder just ensures that you won't have old build files included. The 7-zip operation just zips all of the output.

These are both things that I personally require. I suppose the right move to make them universal would be to create a build script that uses `fs` to delete the output folder, then use a universal zip solution.

**Comment by dennmuel** [comment]
On a site note: if anyone is capable of doing this, maybe a dockerfile (+ docker-compose) could come in handy?

**Comment by dbaratta** [comment]
@dennmuel I'm actually working on a docker file for it now :)

**Comment by jgrifft** [comment]
Would love to have this in docker.  Would make deployment much easier.

**Comment by jakelauer** [comment]
I have literally zero experience with Docker, so I'm glad you guys are into this :)

**Comment by offset25** [comment]
Jgrifft - Do you have instructions on how you built this project and got it up and running? I have experience with docker and creating a docker file, but this project but it will require proper dependencies.

**Comment by haydius** [comment]
**I'm away from my home for a while so not able to pull up exactly what I did but this is off the top of my head so don't take it as 100% accurate. Just to help you along the way 🤔  **

Using Windows 10 with [Ubuntu 20.04 via WSL](https://www.microsoft.com/en-nz/p/ubuntu-2004-lts/9n6svws3rx71)
Installed YarnPKG, NPM, MongoDB, Redis, etc.
Changed `7zip-bin-win` to `7zip-bin-linux` (1.3.0 was the version I used if that matters)
Changed all references of `jlauer.local` to my machine name (can use `localhost` if needed)
It's in a couple places (Notepadd++ or Visual Studio Code to replace all works well)
I used one or more ways to install dependencies as I had a lot of initial issues figuring it out and not sure what did it best lol, shoulda noted the fixes :P
`yarn install`, `npm run-script installall`, etc running from root dir of project, 
Eventually ran `yarn dev` which of course returned more dependencies that were needed (such as chalk) and then once it stopped telling me about dependencies it successfully finished and launched the web app.

I may have taken the long/verbose route as my node_modules directory is quite large.
While not too famiuliar with the package management, my PC did whincge that it appeared several package managers/lock files were detected and recommended using jsutr the one so not sure.

I'm pretty sure I have since broke something when adding a language selector and changing out code fragments throughout the app to support it but that'll be for another session once I'm back.

Keen to check out a docker. I have never used thm but appears to be a much better solution than a full-fledged VM for each project. Currently I either run VM instances or where I can run the code from a self-sustaining folder with their own included dependencies (very basic mockery of docker/virtual-env i suppose)

I'll start one from fresh next week so if no better docs or docker is out, keep tuned for that. 😄

**Comment by jakelauer** [comment]
I did update the project to hopefully not require these changes. Has anyone tried since then? It should be longer have any references to Windows-specific commands or packages.

**Comment by offset25** [comment]
Yeah I tried installing from scratch and getting error. I used regular yarn not yarn classic though.
Please see github issue #338

**Comment by jgrifft** [comment]
I'll be trying again tonight and will update with any progress.

**Comment by offset25** [comment]
what version of npm were you using? I had installed on my windows 10 machine using nvm and set my npm version and used git-bash. I can try installing using ubuntu

**Comment by offset25** [comment]
yes ran into a lot of dependency issues and have a list of dependencies used to install. I had to use an older version of path-to-regexp as the latest version had issues.

**Comment by offset25** [comment]
This is the list of dependencies (loosly) I had to manually install.
npm install yarn
npm install concurrently
npm install nodemon
npm install dotenv-expand
npm install dotenv
npm install -g ts-node
npm install ts-node
npm install react-dev-utils
npm install webpack
npm install webpack-dev-server
npm install typescript
npm install case-sensitive-paths-webpack-plugin
npm install mini-css-extract-plugin
npm install optimize-css-assets-webpack-plugin
npm install postcss-safe-parser
npm install webpack-manifest-plugin
npm install workbox-webpack-plugin
npm install postcss-normalize
npm install express
npm install url-loader
npm install babel-loader
npm install -D @types/express
npm install -D @types/compression
npm install -D @types/cookie-parser
npm install -D @types/express-mongo-sanitize
npm install -D @types/node
npm install -D @sentry/node
npm install webpack-overrides
npm install webpack-cli
npm install -D babel-loader @babel/core @babel/preset-env webpack
npm install -D babel-loader @babel/core @babel/webpack-overrides
npm install -D babel-loader webpack-overrides
npm install babel-preset-react-app
npm install babel-plugin-named-asset-import
npm install style-loader
npm install css-loader
npm install postcss-loader
npm install sass-loader
npm install file-loader
npm install node-sass
npm install postcss-flexbugs-fixes
npm install postcss-preset-env
npm install -D @types/express-mongo-sanitize
npm install -D @types/stream
npm install -D @types/bad-words
npm install @material-ui/core
npm install @material-ui/lab
npm install -D @types/bad-words
npm install bad-words
npm install classnames
npm install es6-promise
npm install linkifyjs/react
npm install linkifyjs
npm install promise.prototype.finally
npm install react
npm install react-copy-to-clipboard
npm install react-dom
npm install react-emoji-render
npm install react-ga
npm install react-helmet
npm install react-icons
npm install react-router
npm install react-router-dom
npm install react-spinners
npm install react-twitter-embed
npm install sanitize-html
npm install shuffle-array
npm install visibilityjs
npm install -D @types/react-router-dom
npm install -D @types/classnames
npm install -D @types/react-helmet
npm install -D @types/linkifyjs
npm install @types/sanitize-html
npm install @types/shuffle-array
npm install @types/path-to-regexp
npm install path-to-regexp
npm i html-webpack-plugin
npm i pnp-webpack-plugin
npm i mini-css-external-plugin
npm i babel-preset-react-app
npm i webpack-overrides
npm i path-to-regexp@2.4.0

**Comment by jakelauer** [comment]
Which folder did you run your install on? It looks like you didn't run it in the right folders. You have to run it in the root folder and the `client` folder

**Comment by offset25** [comment]
yeah they were run in the root folder.

**Comment by jakelauer** [comment]
I mean, if you had to install that many dependencies manually, I think something is just wrong with your local setup.

**Comment by offset25** [comment]
Hrmm. The process I follow is the same as when I work with any react/angular/vue/node project. I use nvm to set the version of the node and then typically run npm install. However in your case its yarn dev is what it said in your instructions. I had to follow the same manual installs on my centos environment as well and I thought it was rather strange that I had to manually install so many dependencies rather than it being automatic.

Is there a particular other command I need to run? Because the yarn dev just doesn't install everything to get it up and running. What node version are you using? And also do I really need to use yarn classic? I'm just using the yarn that installs with npm.

**Comment by jakelauer** [comment]
Did you run `yarn install`? You need to run `yarn install` at root and in `client`.

**Comment by offset25** [comment]
I'm pretty sure I ran npm install, but not yarn install let me try that on root and client. The instructions just said to run yarn dev.

**Comment by jakelauer** [comment]
That's true, I will update the instructions. I also have a local change to improve this process.

**Comment by offset25** [comment]
ok got it to work from a clean install.
I downgraded to node v12.18.0
yarn install on both root and client
on client need to add the following additional dependencies.
yarn add @babel/plugin-transform-react-jsx
yarn add @babel/plugin-transform-react-jsx-self
yarn add @babel/plugin-transform-react-jsx-source

then set jlauer.local to localhost in clients/packages.json for proxy and set jlauer.local to localhost on config/config.ts then configure keys.json

On a windows machine have to make sure you have firewall open from private in order to access.

Thanks for all the help @jakelauer and @jgrifft

**Comment by jakelauer** [comment]
Closing. If you continue to have issues, comment here.
