### ISSUE TITLE
Complaint about copyright system

### ISSUE THREAD

**Issue by DarkErminia** [jakelauer/allbadcards#396]
URL: https://allbad.cards/pack/detail/UGENfZ57O

Problem: I received a message saying the cards "LGBTQ Community", "President Donald Trump" and "Child Labour" were all copyrighted, even though I believe the names not to be owned by any individual or corporation. "LGBTQ Community" I don't think is a copyrighted name, "President Donald Trump" is certainly not copyrighted, as he is a public figure, and usage of his name probably can't be sued, and "Child Labour" is a concept.
Maybe I'm wrong, but I personally feel none of these should be copyrighted.

Errors Seen: Well, yes, but it was separate from this problem. Something like "JSON error ">" detected at position 0" or something like that.

Screenshot of all errors:

https://i.imgur.com/eZ5iCPh.png

**Comment by jakelauer** [comment]
Yes, totally agree. This system was a bit rushed and as such it has a high number of false positives right now. The goal will be to reduce the number of false positives, but I won't be able to eliminate them.

For clarification, even though a phrase may not seem like copyrighted content simply as a set of words, it can still be considered as such in the context of a game of those format, whereby the licensed content is the joke being made, rather than the words themselves.

**Comment by jakelauer** [comment]
This is more lenient now.
