### ISSUE TITLE
AI Player got bugged in the middle of a round

### ISSUE THREAD

**Issue by aarguellesuninorte** [jakelauer/allbadcards#88]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/sharp-starfish-70

2. Describe the problem you experienced
IA user "Fraud Swanson" got bugged after a few rounds and never played his card.

3. Did you see any errors?
Fraud Swanson kept loading...

4. Screenshots - If applicable, add screenshots to help explain your problem.
![imagen](https://user-images.githubusercontent.com/10714325/79940926-adf08200-8428-11ea-80eb-776775628d3d.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser: Firefox
- Device type: Ideapad L340 Gaming Laptop running Win10

**Comment by jakelauer** [comment]
Very strange. I'll take a look.

**Comment by aarguellesuninorte** [comment]
Thanks!

Btw , a little more insight: the room/match had two real players and two AI players.

**Comment by jakelauer** [comment]
I think this is almost certainly a bug that happened because the server restarted during the timer for the random card. I could probably fix this by removing the timer. The timer is... honestly not important at all anyway. I added it to make it seem like the fake players were kinda deciding too as a bit of skeuomorphism.

**Comment by jakelauer** [comment]
This should be fixed now with the removal of AI player timers
